# Generated by Django 5.0.2 on 2024-02-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gamesense',
            field=models.IntegerField(default=0),
        ),
    ]
