# Generated by Django 5.0.2 on 2024-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_user_gamesense'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storygames',
            field=models.IntegerField(default=0),
        ),
    ]
